Repository tmdwo5825-naver-com/BE-CBNU-Mr.CAT_MOM, pull requests merged in 2023-06, with the labels that each got.

#60 Feature: 이미지를 처리한다.
  __pycache__/crud.cpython-311.pyc
  __pycache__/database.cpython-311.pyc
  app/__pycache__/main.cpython-311.pyc
  app/api/__pycache__/deps.cpython-311.pyc
  app/api/deps.py
  app/api/endpoint/__pycache__/router.cpython-311.pyc
  app/api/endpoint/router.py
  app/aws/__pycache__/s3.cpython-311.pyc
  app/aws/s3.py
  app/crud/__pycache__/crud_cat.cpython-311.pyc
  app/crud/crud_cat.py
  app/database/__pycache__/set_mysql.cpython-311.pyc
  app/database/__pycache__/set_redis.cpython-311.pyc
  app/database/set_redis.py
  app/main.py
  requirements.txt
Labels: refactor

#61 fix: redis connection error
  .gitignore
  app/__pycache__/__init__.cpython-311.pyc
  app/__pycache__/main.cpython-311.pyc
  app/__pycache__/models.cpython-311.pyc
  app/__pycache__/schemas.cpython-311.pyc
  app/api/__pycache__/__init__.cpython-311.pyc
  app/api/__pycache__/deps.cpython-311.pyc
  app/api/endpoint/__pycache__/__init__.cpython-311.pyc
  app/api/endpoint/__pycache__/router.cpython-311.pyc
  app/aws/__pycache__/__init__.cpython-311.pyc
  app/aws/__pycache__/s3.cpython-311.pyc
  app/core/__pycache__/__init__.cpython-311.pyc
  app/core/__pycache__/config.cpython-311.pyc
  app/crud/__pycache__/__init__.cpython-311.pyc
  app/crud/__pycache__/crud_cat.cpython-311.pyc
  app/crud/crud_cat.py
  app/database/__pycache__/__init__.cpython-311.pyc
  app/database/__pycache__/set_mysql.cpython-311.pyc
  app/database/__pycache__/set_redis.cpython-311.pyc
  app/database/set_redis.py
  app/main.py
  docker-compose.yml
Labels: bug

#63 ci/cd: write ci/cd pipeline
  .github/workflows/docker-deploy.yml
  app/database/set_redis.py
Labels: ci/cd

#64 fix: invalid file name
  .github/workflows/docker-deploy.yml
Labels: ci/cd

#66 Refactor: 이미지에 대한 예외처리 및 디렉토리 구조 변경
  app/__pycache__/__init__.cpython-311.pyc
  app/__pycache__/main.cpython-311.pyc
  app/__pycache__/models.cpython-311.pyc
  app/__pycache__/schemas.cpython-311.pyc
  app/api/__pycache__/__init__.cpython-311.pyc
  app/api/__pycache__/deps.cpython-311.pyc
  app/api/common/__init__.py
  app/api/common/get_cat_tower.py
  app/api/common/process_image.py
  app/api/endpoint/__pycache__/__init__.cpython-311.pyc
  app/api/endpoint/__pycache__/router.cpython-311.pyc
  app/api/endpoint/router.py
  app/aws/__pycache__/__init__.cpython-311.pyc
  app/aws/__pycache__/s3.cpython-311.pyc
  app/aws/s3.py
  app/core/__pycache__/__init__.cpython-311.pyc
  app/core/__pycache__/config.cpython-311.pyc
  app/crud/__pycache__/__init__.cpython-311.pyc
  app/crud/__pycache__/crud_cat.cpython-311.pyc
  app/crud/crud_cat.py
  app/crud/crud_mysql.py
  app/crud/crud_redis.py
  app/database/__pycache__/__init__.cpython-311.pyc
  app/database/__pycache__/set_mysql.cpython-311.pyc
  app/database/__pycache__/set_redis.cpython-311.pyc
  app/database/set_mysql.py
  app/database/set_redis.py
  app/database/test.py
  app/models.py
Labels: refactor

#68 bug: s3에 업로드한 객체에 접근하지 못하는 오류를 해결한다.
  app/api/common/process_image.py
  app/api/endpoint/router.py
  app/aws/s3.py
Labels: bug

#69 infra: python의 이미지를 더 가벼운걸로 바꾼다.
  Dockerfile
Labels: ci/cd

#70 infra: docker image와 빌드 환경을 최적화한다.
  Dockerfile
  requirements.txt
Labels: ci/cd

#72 [feature] 업로드 시간을 처리하는 함수를 개발한다.
  .gitignore
  app/api/common/get_cat_tower.py
  app/api/common/process_image.py
  app/api/common/process_time.py
  app/api/endpoint/router.py
  app/aws/s3.py
  app/crud/crud_mysql.py
  app/crud/crud_redis.py
  app/models.py
  app/schemas.py
Labels: feature

#74 mysql table name cat_mom2로 수정
  app/models.py
Labels: bug

#75 refactor: change redis connection name
  app/database/set_redis.py
Labels: refactor

#77 [bug] 자잘한 버그 수정
  app/api/common/process_time.py
  app/crud/crud_redis.py
Labels: bug

#79 [bug] db가 꺼지는 문제를 해결한다.
  app/crud/crud_mysql.py
Labels: bug
