Repository tmdwo5825-naver-com/BE-CBNU-Mr.CAT_MOM, pull requests merged in 2023-05, with the labels that each got.

#12 Feature: post, get요청을 담당하는 router를 개발한다.
  router/router.py
Labels: feature

#15 Refactor: orm model과 router를 수정한다.
  crud.py
  models.py
  router/router.py
  schemas.py
Labels: refactor

#17 feature: redis 서버를 설정하고 연결한다.
  database/set_mysql.py
  database/set_redis.py
Labels: feature

#19 refactor: crud 함수를 깔끔하게 수정한다.
  crud.py
Labels: refactor

#20 refactor: 테이블 이름을 변경한다.
  models.py
Labels: refactor

#24 refactor: s3버킷에 업로드할 객체의 이름을 적용한다.
  aws/s3.py
  router/router.py
Labels: refactor

#26 Bug: main:app이 실행되지 않는 문제를 해결한다.
  main.py
  router/router.py
Labels: bug

#28 Bug: 서버가 실행되지 않는 문제를 해결한다.
  aws/s3.py
  database/db.py
  main.py
Labels: bug

#30 Refactor: core패키지를 분리한다.
  .idea/.gitignore
  aws/s3.py
  core/__init__.py
  core/config.py
  database/set_mysql.py
  database/set_redis.py
Labels: refactor

#33 bug: 데이터를 전송받지 못하는 오류를 해결한다.
  router/router.py
  schemas.py
Labels: bug

#34 bug: s3객체를 업로드하지 못하는 문제를 해결한다.
  aws/s3.py
  core/config.py
  crud.py
  models.py
  router/router.py
Labels: bug

#36 Refactor: Crud를 패키지로 분리한다.
  crud.py
  crud/__init__.py
  crud/crud_cat.py
  router/__pycache__/__init__.cpython-311.pyc
  router/__pycache__/router.cpython-311.pyc
  router/router.py
Labels: refactor

#38 refactor: s3객체의 public권한을 부여한다.
  aws/s3.py
Labels: refactor

#40 feature: crud함수를 개발한다.
  crud/crud_cat.py
  database/set_redis.py
  router/router.py
Labels: feature

#43 Feature: redis 저장 및 조회 함수를 개발한다.
  api/__init__.py
  api/__pycache__/__init__.cpython-311.pyc
  api/__pycache__/deps.cpython-311.pyc
  api/deps.py
  api/endpoints/__init__.py
  api/endpoints/__pycache__/__init__.cpython-311.pyc
  api/endpoints/__pycache__/router.cpython-311.pyc
  api/endpoints/router.py
  crud/__pycache__/__init__.cpython-311.pyc
  crud/__pycache__/crud_cat.cpython-311.pyc
  crud/crud_cat.py
  router/__pycache__/router.cpython-311.pyc
Labels: feature

#45 Refactor: 캣타워를 추가하고 디비에 저장한다.
  api/deps.py
  api/endpoints/router.py
  crud/crud_cat.py
  models.py
  schemas.py
Labels: refactor

#47 refactor: app디렉토리 추가
  .idea/.gitignore
  .idea/cat_mom.iml
  .idea/modules.xml
  .idea/vcs.xml
  __pycache__/__init__.cpython-311.pyc
  __pycache__/main.cpython-311.pyc
  __pycache__/models.cpython-311.pyc
  __pycache__/schemas.cpython-311.pyc
  api/__pycache__/__init__.cpython-311.pyc
  api/__pycache__/deps.cpython-311.pyc
  api/endpoints/__pycache__/__init__.cpython-311.pyc
  api/endpoints/__pycache__/router.cpython-311.pyc
  api/endpoints/router.py
  app/LICENSE
  app/__init__.py
  app/api/__init__.py
  app/api/deps.py
  app/api/endpoint/__init__.py
  app/api/endpoint/router.py
  app/aws/__init__.py
  app/aws/s3.py
  app/common/__init__.py
  app/common/dependencies.py
  app/core/__init__.py
  app/core/config.py
  app/crud/__init__.py
  app/crud/crud_cat.py
  app/database/__init__.py
  app/database/set_mysql.py
  app/database/set_redis.py
  app/database/test.py
  app/main.py
  app/models.py
  app/schemas.py
  crud/__pycache__/__init__.cpython-311.pyc
  crud/__pycache__/crud_cat.cpython-311.pyc
  main.py
Labels: refactor

#49 refactor: main.py의 경로를 변경한다.
  main.py
Labels: refactor

#51 feature: redis, mysql db의 데이터를 조회하는 api를 개발한다.
  app/api/deps.py
  app/api/endpoint/router.py
  app/crud/crud_cat.py
Labels: feature

#53 feature: 이미지의 컨텐츠 타입을 추가한다.
  app/api/deps.py
  app/api/endpoint/router.py
  app/aws/s3.py
  app/models.py
Labels: feature

#55 feature: 캣타워 데이터를 카운트하여 반환하는 api를 개발한다.
  app/api/deps.py
  app/api/endpoint/router.py
  app/common/dependencies.py
  app/crud/crud_cat.py
Labels: feature
